# Generated by Django 3.2.10 on 2022-03-03 05:23

import articles.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('category_favorite', models.BooleanField(default=False)),
                ('category_featured', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=240)),
                ('text', tinymce.models.HTMLField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=240, null=True)),
            ],
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=articles.models.upload_articles)),
                ('is_primary', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('have_children', models.BooleanField(default=False, verbose_name='Main Category')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=240, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='articles.articlecategory')),
            ],
            options={
                'ordering': ['-have_children'],
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.ArticleCategory'),
        ),
        migrations.AddField(
            model_name='article',
            name='city',
            field=models.ManyToManyField(blank=True, to='frontend.City'),
        ),
    ]
