# Generated by Django 3.2.7 on 2021-09-25 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articlecategory',
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='have_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='articles.articlecategory'),
        ),
    ]
