# Generated by Django 3.2.7 on 2021-09-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210925_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='have_children',
            field=models.BooleanField(default=False, verbose_name='Main Category'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
