# Generated by Django 3.2.7 on 2021-09-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210925_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['-have_children']},
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=240, null=True),
        ),
    ]
