# Generated by Django 3.1.6 on 2021-09-27 04:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_featured'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
