# Generated by Django 3.2.7 on 2021-09-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210927_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.ArticleCategory'),
        ),
    ]
