# Generated by Django 3.2.3 on 2021-09-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='category_featured',
            field=models.BooleanField(default=False),
        ),
    ]
