# Generated by Django 3.2.3 on 2021-09-29 14:38

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210928_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlephotos',
            name='image',
            field=models.ImageField(upload_to=articles.models.upload_articles),
        ),
    ]
