# Generated by Django 3.2.3 on 2021-09-29 14:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articlephotos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
