# Generated by Django 3.2.9 on 2021-11-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('approve', models.BooleanField(default=False, verbose_name='Αποδέχομαι τους όρους χρήσης')),
                ('first_name', models.CharField(blank=True, max_length=220, null=True)),
                ('last_name', models.CharField(blank=True, max_length=220, null=True)),
                ('gender', models.CharField(choices=[('a', 'Άνδρας'), ('b', 'Γυναίκα'), ('c', 'Δε επιθυμώ να απαντήσω')], default='c', max_length=1)),
            ],
        ),
    ]
