# Generated by Django 3.2.10 on 2022-03-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_readed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='ΟΝΟΜΑΤΕΠΩΝΥΜΟ')),
                ('title', models.CharField(max_length=200, verbose_name='ONOMA ΕΤΑΙΡΙΑΣ')),
                ('phone', models.CharField(max_length=15, verbose_name='ΤΗΛΕΦΩΝΟ ΕΠΙΚΟΙΝΩΝΙΑΣ')),
                ('afm', models.CharField(max_length=10, unique=True, verbose_name='ΑΦΜ')),
                ('priority', models.CharField(choices=[('1', 'ΠΛΑΝΟ ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 50/ΜΗΝΑ'), ('2', 'ΠΛΑΝΟ ΓΙΑ ΥΠΗΡΕΣΙΕΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 35/ΜΗΝΑ')], default='3', max_length=1, verbose_name='ΠΛΑΝΟ')),
                ('city', models.CharField(max_length=150, verbose_name='ΠΟΛΗ')),
            ],
            options={
                'verbose_name_plural': 'ΕΓΓΡΑΦΕΣ ΕΠΙΧΕΙΡΗΣΕΩΝ',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('a', 'ΓΕΝΙΚΗ ΕΡΩΤΗΣΗ'), ('b', 'ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ')], default='a', max_length=1, verbose_name='ΚΑΤΗΓΟΡΙΑ')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200, verbose_name='ΤΙΤΛΟΣ')),
                ('text', models.TextField(verbose_name='ΠΕΡΙΓΡΑΦΗ')),
            ],
        ),
    ]
