# Generated by Django 3.2.8 on 2021-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20211031_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscontact',
            options={'verbose_name_plural': 'ΕΓΓΡΑΦΕΣ ΕΠΙΧΕΙΡΗΣΕΩΝ'},
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='ONOMA ΕΤΑΙΡΙΑΣ'),
            preserve_default=False,
        ),
    ]
