# Generated by Django 3.2.9 on 2021-11-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20211031_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('a', 'ΓΕΝΙΚΗ ΕΡΩΤΗΣΗ'), ('b', 'ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ')], default='a', max_length=1, verbose_name='ΚΑΤΗΓΟΡΙΑ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TextField(verbose_name='ΠΕΡΙΓΡΑΦΗ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=200, verbose_name='ΤΙΤΛΟΣ'),
        ),
    ]
