# Generated by Django 3.2.8 on 2022-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20211128_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscontact',
            name='priority',
            field=models.CharField(choices=[('1', 'ΠΛΑΝΟ ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 50/ΜΗΝΑ'), ('2', 'ΠΛΑΝΟ ΓΙΑ ΥΠΗΡΕΣΙΕΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 35/ΜΗΝΑ')], default='3', max_length=1, verbose_name='ΠΛΑΝΟ'),
        ),
    ]
