# Generated by Django 3.2.8 on 2021-10-18 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxes_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('permission_grand', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
