# Generated by Django 3.2.10 on 2022-03-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ΟΝΟΜΑΤΕΠΩΝΥΜΟ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permission_grand',
            field=models.BooleanField(default=False, verbose_name='ΕΠΙΒΑΙΒΑΙΩΣΗ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='ΤΗΛΕΦΩΝΟ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='taxes_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='ΑΦΜ'),
        ),
    ]
