# Generated by Django 3.1.6 on 2021-10-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_auto_20211021_0949'),
        ('accounts', '0002_auto_20211020_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcategories',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='instagramcategories',
            name='title',
            field=models.CharField(max_length=200, verbose_name='ΤΙΤΛΟΣ'),
        ),
        migrations.AlterField(
            model_name='instagramlink',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_links', to='accounts.instagramcategories', verbose_name='ΚΑΤΗΓΟΡΙΑ'),
        ),
        migrations.AlterField(
            model_name='instagramlink',
            name='title',
            field=models.CharField(max_length=200, verbose_name='ΤΙΤΛΟΣ'),
        ),
    ]
