# Generated by Django 3.2.8 on 2021-10-22 12:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0020_auto_20211021_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120, verbose_name='Τίτλος')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Σχόλια')),
                ('timestamp', models.DateField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.category', verbose_name='Κατηγορία')),
            ],
            options={
                'verbose_name_plural': '3. Κατηγορίες Site',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('is_offer', models.BooleanField(default=False, verbose_name='Προσφορά')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('sku', models.CharField(blank=True, max_length=150, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=240, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Αρχική Τιμή')),
                ('price_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Εκπτωτική Τιμή')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Τιμή Πώλησης')),
                ('category', models.ManyToManyField(blank=True, to='catalogue.Category', verbose_name='Κατηγορία')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
