# Generated by Django 3.2.10 on 2022-03-03 06:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120, verbose_name='Τίτλος')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Σχόλια')),
                ('timestamp', models.DateField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.servicecategory', verbose_name='Κατηγορία')),
            ],
            options={
                'verbose_name_plural': '3. Κατηγορίες Site',
            },
        ),
        migrations.DeleteModel(
            name='CompanyCategory',
        ),
    ]
