# Generated by Django 3.2.8 on 2022-03-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20220303_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': '1. Κατηγορίες Service'},
        ),
    ]
