# Generated by Django 3.2.8 on 2021-11-02 13:42

import catalogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=catalogue.models.upload_to),
        ),
    ]
