# Generated by Django 3.2.8 on 2021-11-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
