# Generated by Django 3.2.8 on 2021-12-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20211201_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'ΠΡΟΪΟΝΤΑ'},
        ),
    ]
