# Generated by Django 3.2.10 on 2022-03-03 05:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ΚΑΤΗΓΟΡΙΑ ΑΓΓΕΛΙΑΣ',
                'verbose_name_plural': 'ΚΑΤΗΓΟΡΙΕΣ ΑΓΓΕΛΙΑΣ',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobPostings.jobcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'ΑΓΓΕΛΙΑ',
                'verbose_name_plural': 'ΑΓΓΕΛΙΕΣ',
            },
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
