# Generated by Django 3.2.3 on 2021-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPostings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcategory',
            options={'verbose_name': 'ΚΑΤΗΓΟΡΙΑ ΑΓΓΕΛΙΑΣ', 'verbose_name_plural': 'ΚΑΤΗΓΟΡΙΕΣ ΑΓΓΕΛΙΑΣ'},
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'verbose_name': 'ΑΓΓΕΛΙΑ', 'verbose_name_plural': 'ΑΓΓΕΛΙΕΣ'},
        ),
        migrations.AddField(
            model_name='jobpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
