# Generated by Django 3.2.3 on 2021-10-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPostings', '0003_auto_20211006_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
