# Generated by Django 3.2.10 on 2022-03-03 05:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=220)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('a', 'Big Banner'), ('b', 'Medium Banner')], default='a', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('image', models.ImageField(help_text='1370*385', upload_to='cities/')),
                ('title', models.CharField(max_length=220, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True)),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
