# Generated by Django 3.2.3 on 2021-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default='', upload_to='cities/'),
            preserve_default=False,
        ),
    ]
