# Generated by Django 3.2.3 on 2021-10-05 12:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20211004_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
