# Generated by Django 3.2.3 on 2021-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_city_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
