# Generated by Django 3.2.8 on 2021-11-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=220)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
