# Generated by Django 3.2.8 on 2021-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('a', 'BIG Banner'), ('b', 'Medium Banner')], default='a', max_length=1),
        ),
    ]
