# Generated by Django 3.2.8 on 2021-11-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_banner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('a', 'Big Banner'), ('b', 'Medium Banner')], default='a', max_length=1),
        ),
    ]
