# Generated by Django 3.2.8 on 2022-01-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_alter_banner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(help_text='1370*385', upload_to='cities/'),
        ),
    ]
