# Generated by Django 3.2.7 on 2021-09-28 04:12

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(help_text='400*400', null=True, upload_to=companies.models.upload_to),
        ),
    ]
