# Generated by Django 3.2.8 on 2022-03-05 15:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companyservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycategory',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='companies/catalogue/upload-big-images/'),
        ),
        migrations.AddField(
            model_name='companycategory',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
