# Generated by Django 3.2.3 on 2021-09-28 04:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='priority',
            field=models.CharField(choices=[('1', 'First Choice'), ('2', 'Second Choice'), ('3', 'Third Choice')], default='3', max_length=1),
        ),
    ]
