# Generated by Django 3.2.3 on 2021-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='companies/logo/'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_ends',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(help_text='400*400', null=True, upload_to='companies/images/'),
        ),
    ]
