# Generated by Django 3.2.3 on 2021-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20210929_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='count',
            new_name='counter',
        ),
        migrations.AlterField(
            model_name='company',
            name='priority',
            field=models.CharField(choices=[('1', 'First. Subscription Cost:  50'), ('2', 'Second. Subscription Cost: 40'), ('3', 'Third. Subscription Cost:  30')], default='3', max_length=1),
        ),
    ]
