# Generated by Django 3.2.3 on 2021-10-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companycategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
