# Generated by Django 3.2.3 on 2021-10-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20211004_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('1', 'ΕΜΠΟΡΙΟ'), ('2', 'ΕΣΤΙΑΣΗ'), ('3', 'ΥΠΗΡΕΣΙΕΣ'), ('4', 'ΜΕΙΚΤΟ')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='company',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='first_choice',
            field=models.BooleanField(default=False),
        ),
    ]
