# Generated by Django 3.2.3 on 2021-10-06 14:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_companyinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
