# Generated by Django 3.2.3 on 2021-10-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20211006_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
