# Generated by Django 3.0.1 on 2021-10-08 04:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_companyservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyitems',
            options={'verbose_name': 'ΠΡΟΪΟΝ', 'verbose_name_plural': 'ΠΡΟΪΟΝΤΑ'},
        ),
        migrations.AlterModelOptions(
            name='companyservice',
            options={'verbose_name': 'ΥΠΗΡΕΣΙΑ', 'verbose_name_plural': 'ΥΠΗΡΕΣΙΕΣ'},
        ),
        migrations.AddField(
            model_name='companyitems',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyitems',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='companies.Company'),
        ),
    ]
