# Generated by Django 3.2.8 on 2021-10-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_auto_20211009_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
