# Generated by Django 3.1.6 on 2021-10-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20211020_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='priority',
            field=models.CharField(choices=[('1', 'First. Subscription Cost:  100'), ('2', 'Second. Subscription Cost: 40'), ('3', 'Third. Subscription Cost:  20')], default='3', max_length=1),
        ),
    ]
