# Generated by Django 3.2.8 on 2021-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_auto_20211021_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
