# Generated by Django 3.2.8 on 2021-10-27 06:50

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_companyservice_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='address',
            field=models.CharField(blank=True, max_length=220, verbose_name='ΔΙΕΥΘΥΝΣΗ'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='ΦΟΝΤΟ'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ΚΙΝΗΤΟ'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='ΣΕΛΙΔΑ FACEBOOK'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='ΣΕΛΙΔΑ INSTAGRAM'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='ΤΗΛΕΦΩΝΟ'),
        ),
    ]
