# Generated by Django 3.2.8 on 2021-10-27 07:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_auto_20211027_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='image',
            field=models.ImageField(null=True, upload_to='services', verbose_name='ΕΙΚΟΝΑ'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='ΠΕΡΙΓΡΑΦΗ'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΤΙΜΗ'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='ΠΕΡΙΓΡΑΦΗ'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='title',
            field=models.CharField(max_length=250, verbose_name='ΤΙΤΛΟΣ'),
        ),
    ]
