# Generated by Django 3.2.8 on 2021-11-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_auto_20211027_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='background_image',
        ),
        migrations.AddField(
            model_name='company',
            name='service_title',
            field=models.CharField(default='ΥΠΗΡΕΣΙΕΣ', max_length=220),
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='companies.company')),
            ],
        ),
    ]
