# Generated by Django 3.2.8 on 2021-11-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20211103_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyservice',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='image',
            field=models.ImageField(upload_to='companies/images/'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='companies/logos/'),
        ),
        migrations.AlterField(
            model_name='companyservice',
            name='image',
            field=models.ImageField(null=True, upload_to='companies/service/images/', verbose_name='ΕΙΚΟΝΑ'),
        ),
    ]
