# Generated by Django 3.2.8 on 2021-11-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_auto_20211105_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='companies/categories/'),
        ),
    ]
