# Generated by Django 3.2.8 on 2021-11-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_companycategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyimage',
            name='background_img',
            field=models.BooleanField(default=False),
        ),
    ]
