# Generated by Django 3.2.8 on 2021-11-17 17:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_companyimage_background_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='google_map_location',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyimage',
            name='background_img',
            field=models.BooleanField(default=False, verbose_name='ΕΞΩΦΥΛΛΟ'),
        ),
    ]
