# Generated by Django 3.2.8 on 2021-11-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_auto_20211117_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='google_map_location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
