# Generated by Django 3.2.8 on 2021-11-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_alter_company_google_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='google_map_location',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
