# Generated by Django 3.2.9 on 2021-11-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_alter_company_google_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_companies', to='companies.CompanyCategory'),
        ),
    ]
