# Generated by Django 3.2.8 on 2022-01-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_alter_company_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycategory',
            options={'verbose_name': 'ΚΑΤΗΓΟΡΙΑ ΕΤΑΙΡΙΑΣ', 'verbose_name_plural': '5. ΚΑΤΗΓΟΡΙΕΣ ΕΤΑΙΡΙΩΝ'},
        ),
        migrations.AddField(
            model_name='company',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='CompanyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_method', models.CharField(choices=[('a', 'ΤΡΑΠΕΖΑ ΠΕΙΡΑΙΩΣ'), ('b', 'ΕΘΝΙΚΗ ΤΡΑΠΕΖΑ'), ('c', 'ΜΕΤΡΗΤΑ')], default='a', max_length=1)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company')),
            ],
        ),
    ]
