# Generated by Django 3.2.8 on 2022-01-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_auto_20220109_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyorder',
            options={'verbose_name': 'ΤΙΜΟΛΟΓΙΟ', 'verbose_name_plural': '1.1 ΤΙΜΟΛΟΓΙΑ'},
        ),
        migrations.AlterModelOptions(
            name='companypayment',
            options={'verbose_name': 'ΠΛΗΡΩΜΗ', 'verbose_name_plural': '1.2 ΠΛΗΡΩΜΕΣ'},
        ),
        migrations.AddField(
            model_name='company',
            name='admin_active',
            field=models.BooleanField(default=False, verbose_name='ΓΕΝΙΚΟΣ ΔΙΑΚΟΠΤΗΣ'),
        ),
    ]
