# Generated by Django 3.2.8 on 2022-01-10 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_auto_20220109_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['featured', 'first_choice', 'priority'], 'verbose_name_plural': '1. ΕΠΙΧΕΙΡΗΣΕΙΣ'},
        ),
        migrations.AlterField(
            model_name='company',
            name='first_choice',
            field=models.BooleanField(default=False, verbose_name='ΠΡΟΤΕΡΙΟΤΗΤΑ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='priority',
            field=models.CharField(choices=[('1', 'ΠΛΑΝΟ ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 40/ΜΗΝΑ'), ('2', 'ΠΛΑΝΟ ΓΙΑ ΥΠΗΡΕΣΙΕΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 30/ΜΗΝΑ')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=False, verbose_name='ΚΑΤΑΣΤΑΣΗ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ΥΠΟΛΟΙΠΟ'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company', verbose_name='ΕΤΑΙΡΙΑ'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='date',
            field=models.DateField(verbose_name='ΗΜΕΡΟΜΗΝΙΑ'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='title',
            field=models.CharField(max_length=220, null=True, verbose_name='ΤΙΤΛΟΣ'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ΑΞΙΑ'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company', verbose_name='ΕΤΑΙΡΙΑ'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='date',
            field=models.DateField(verbose_name='ΗΜΕΡΟΜΗΝΙΑ'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='title',
            field=models.CharField(max_length=220, null=True, verbose_name='ΤΙΤΛΟΣ'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ΑΞΙΑ'),
        ),
        migrations.CreateModel(
            name='CompanyHitCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.CharField(max_length=220)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='companies.company')),
            ],
        ),
    ]
