# Generated by Django 3.2.8 on 2022-01-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_auto_20220110_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ServiceHitCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.CharField(max_length=220)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='companies.companyservice')),
            ],
        ),
    ]
