# Generated by Django 3.2.8 on 2022-01-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0037_auto_20220110_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
