# Generated by Django 3.2.8 on 2022-01-12 16:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_companyservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='ΠΕΡΙΓΡΑΦΗ'),
        ),
    ]
