# Generated by Django 3.2.8 on 2022-01-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0039_alter_companyservice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='text',
            field=models.TextField(blank=True, verbose_name='ΠΕΡΙΓΡΑΦΗ'),
        ),
    ]
