# Generated by Django 3.2.8 on 2022-02-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0040_alter_companyservice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='logo_site',
            field=models.ImageField(blank=True, help_text='LOGO ΣΤΗΝ ΔΙΚΗ ΜΑΣ ΣΕΛΙΔΑ 400*600', null=True, upload_to='companies/logo_site/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='priority',
            field=models.CharField(choices=[('1', 'ΠΛΑΝΟ ΓΙΑ ΕΠΙΧΕΙΡΗΣΕΙΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 50/ΜΗΝΑ'), ('2', 'ΠΛΑΝΟ ΓΙΑ ΥΠΗΡΕΣΙΕΣ: ΚΟΣΤΟΣ ΣΥΝΔΡΟΜΗΣ 35/ΜΗΝΑ')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='lOGO ΣΤΗΝ ΣΕΛΙΔΑ ΤΟΥ ΠΕΛΑΤΗ 120*40', upload_to='companies/logos/'),
        ),
    ]
