# Generated by Django 3.2.8 on 2022-03-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_alter_company_google_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='extra_css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
