# Generated by Django 3.2.7 on 2021-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAds', '0002_myad_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='myad',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
