# Generated by Django 3.0.1 on 2021-09-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAds', '0003_myad_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myad',
            name='category',
            field=models.CharField(choices=[('a', 'Navbar Ads. Image size 728*90'), ('b', 'Main Ads'), ('c', 'Page Ads')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='myad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
