# Generated by Django 3.2.7 on 2021-09-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAds', '0004_auto_20210926_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
