# Generated by Django 3.2.3 on 2021-09-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20210928_1559'),
        ('myAds', '0005_alter_myad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myad',
            name='article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.articlecategory'),
        ),
        migrations.AlterField(
            model_name='myad',
            name='category',
            field=models.CharField(choices=[('a', 'Navbar Ads. Image size 728*90'), ('b', 'Main Ads'), ('c', 'Page Ads'), ('d', 'Category Ads')], default='a', max_length=1),
        ),
    ]
