# Generated by Django 3.2.3 on 2021-09-29 14:38

from django.db import migrations, models
import django.db.models.deletion
import myAds.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articlephotos_image'),
        ('myAds', '0006_auto_20210928_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myad',
            name='article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_add', to='articles.articlecategory'),
        ),
        migrations.AlterField(
            model_name='myad',
            name='image',
            field=models.ImageField(upload_to=myAds.models.upload_ad),
        ),
    ]
