# Generated by Django 3.2.3 on 2021-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAds', '0007_auto_20210929_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myad',
            name='image',
            field=models.ImageField(upload_to='my_adds/%Y/%m/%d/'),
        ),
    ]
