# Generated by Django 3.2.3 on 2021-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAds', '0009_auto_20211006_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
