# Generated by Django 3.1.6 on 2021-10-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAds', '0014_alter_myad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
