# Generated by Django 3.2.8 on 2021-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAds', '0015_auto_20211020_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
